CREATE TABLE  T_USERS
(
  	ID 								NUMBER(20) NOT NULL,
  	USER_NAME						VARCHAR2(16) NOT NULL,
  	PASS_WORD						VARCHAR2(64) NOT NULL,
  	NICK_NAME						VARCHAR2(20) NOT NULL,
  	USER_CODE						VARCHAR2(64) NOT NULL,
  	
  	USER_STATUS						CHAR(1) DEFAULT '1' NOT NULL,
    PASSWD_SALT						VARCHAR2(3) NOT NULL,
  	
    USER_SEX						CHAR(1) DEFAULT 0 NOT NULL,
  	USER_EMAIL						VARCHAR2(32) DEFAULT ' ' NOT NULL,
    USER_PHONE						VARCHAR2(20) DEFAULT ' ' NOT NULL,
    
    CSS_ID							VARCHAR2(50) DEFAULT ' ' NOT NULL,
    ROLE_ID							NUMBER(20) DEFAULT 0 NOT NULL,
    DEPARTMENT_ID					NUMBER(20) NOT NULL,
    ORG_ID							NUMBER(20) NOT NULL,
    
    LAST_ACCESS_IP					VARCHAR(15) DEFAULT ' ' NOT NULL,
    LAST_LOGIN_TIME					DATE,
    LAST_ACCESS_TIME				DATE,
    ONLINE_TIME						NUMBER(6) DEFAULT 0	NOT NULL,
    ACCESS_MODULE					VARCHAR(50) DEFAULT ' ' NOT NULL,
	
    IS_LOGIN						CHAR(1) DEFAULT '0' NOT NULL,
    IS_DEL    						CHAR(1) DEFAULT '0' NOT NULL,
    CREATE_TIME  					DATE NOT NULL,
    UPDATE_TIME 					DATE NOT NULL,
    CREATE_USERID 					NUMBER(20) DEFAULT 0 NOT NULL,
    UPDATE_USERID 					NUMBER(20) DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE T_USERS IS '用户表';
COMMENT ON COLUMN T_USERS.USER_NAME  IS '登陆名称';
COMMENT ON COLUMN T_USERS.PASS_WORD  IS '登录密码';
COMMENT ON COLUMN T_USERS.NICK_NAME  IS '用户昵称';
COMMENT ON COLUMN T_USERS.USER_CODE  IS '用户编码(默认登录名称的hashcode)';
COMMENT ON COLUMN T_USERS.USER_STATUS  IS '用户状态(-1:不存在或错误, 0:停用, 1:启用, 2:超级管理员)';
COMMENT ON COLUMN T_USERS.PASSWD_SALT  IS '密码盐值(默认随机取部分用户名)';
COMMENT ON COLUMN T_USERS.USER_SEX  IS '用户性别(0:男, 1:女)';
COMMENT ON COLUMN T_USERS.USER_EMAIL  IS '用户邮箱';
COMMENT ON COLUMN T_USERS.USER_PHONE  IS '用户电话';
COMMENT ON COLUMN T_USERS.CSS_ID  IS '样式ID';
COMMENT ON COLUMN T_USERS.ROLE_ID  IS '角色ID';
COMMENT ON COLUMN T_USERS.DEPARTMENT_ID  IS '部门ID';
COMMENT ON COLUMN T_USERS.ORG_ID  IS '机构ID';
COMMENT ON COLUMN T_USERS.LAST_ACCESS_IP  IS '最后访问IP';
COMMENT ON COLUMN T_USERS.LAST_LOGIN_TIME  IS '最后登录时间';
COMMENT ON COLUMN T_USERS.LAST_ACCESS_TIME  IS '最后访问时间';
COMMENT ON COLUMN T_USERS.ONLINE_TIME  IS '在线累计时长';
COMMENT ON COLUMN T_USERS.ACCESS_MODULE  IS '当前访问模块';
COMMENT ON COLUMN T_USERS.IS_DEL  IS '是否删除(0:否, 1:删)';
COMMENT ON COLUMN T_USERS.IS_LOGIN  IS '是否已登录(0:否, 1:是)';
COMMENT ON COLUMN T_USERS.CREATE_TIME  IS '创建时间';
COMMENT ON COLUMN T_USERS.UPDATE_TIME  IS '最后更新时间';
COMMENT ON COLUMN T_USERS.CREATE_USERID  IS '创建者ID';
COMMENT ON COLUMN T_USERS.UPDATE_USERID  IS '更新者ID';

CREATE INDEX INDEX_T_USERS_DEPARTMENT_ID ON T_USERS(DEPARTMENT_ID);
CREATE INDEX INDEX_T_USERS_ORG_ID ON T_USERS(ORG_ID);