CREATE TABLE T_ROLE_MENU(
	ID NUMBER(20) NOT NULL,
	MENU_ID NUMBER(20) NOT NULL,
	ROLE_ID NUMBER(20) NOT NULL,
	PRIMARY KEY (ID)
);

COMMENT ON TABLE T_ROLE_MENU IS '角色菜单关联';
COMMENT ON COLUMN T_ROLE_MENU.MENU_ID  IS '菜单id';
COMMENT ON COLUMN T_ROLE_MENU.ROLE_ID  IS '角色id';

CREATE INDEX INDEX_T_ROLE_MENU_ROLE_ID ON T_ROLE_MENU(ROLE_ID);