CREATE TABLE T_ROLE_USER(
	ID NUMBER(20) NOT NULL,
	USER_ID NUMBER(20) NOT NULL,
	ROLE_ID NUMBER(20) NOT NULL,
	PRIMARY KEY (ID)
);

COMMENT ON TABLE T_ROLE_USER IS '角色用户关联';
COMMENT ON COLUMN T_ROLE_USER.USER_ID  IS '用户id';
COMMENT ON COLUMN T_ROLE_USER.ROLE_ID  IS '角色id';

CREATE INDEX INDEX_T_ROLE_USER_USER_ID ON T_ROLE_USER(USER_ID);