CREATE TABLE T_LOGGERS(
	ID NUMBER(20) NOT NULL,
	USER_ID NUMBER(20) NOT NULL,
	USER_NICKNAME VARCHAR2(50) NOT NULL,
	OPTOR_TYPE CHAR(1) NOT NULL,
	ENTITY_NAME VARCHAR2(50) NOT NULL,
	MODEL_TITLE VARCHAR2(50) NOT NULL,
	MODEL_ID NUMBER(20) NOT NULL,
	OPTOR_TIME DATE NOT NULL,
	OPTOR_DETAIL VARCHAR2(250) NOT NULL,
	PRIMARY KEY (ID)
);

COMMENT ON TABLE T_LOGGERS IS '日志表';
COMMENT ON COLUMN T_LOGGERS.USER_ID  IS '操作的用户ID';
COMMENT ON COLUMN T_LOGGERS.USER_NICKNAME IS '操作用户昵称';
COMMENT ON COLUMN T_LOGGERS.OPTOR_TYPE  IS 'CRUD类型(0:添加;1:修改;2:删除)';
COMMENT ON COLUMN T_LOGGERS.ENTITY_NAME  IS '操作的实体业务类型名称(使用枚举定义,如:用户管理)';
COMMENT ON COLUMN T_LOGGERS.MODEL_TITLE  IS '实体标题(自定义设置,如菜单B)';
COMMENT ON COLUMN T_LOGGERS.MODEL_ID  IS '操作的实体ID';
COMMENT ON COLUMN T_LOGGERS.OPTOR_TIME  IS '操作时间';
COMMENT ON COLUMN T_LOGGERS.OPTOR_DETAIL  IS '操作详细说明';

CREATE INDEX INDEX_T_LOGGERS_USER_ID ON T_LOGGERS(USER_ID);
CREATE INDEX INDEX_T_LOGGERS_OPTOR_TYPE ON T_LOGGERS(OPTOR_TYPE);