CREATE TABLE T_ROLES
(
ID NUMBER(20) NOT NULL,
ROLE_NAME VARCHAR2(50) NOT NULL,
ROLE_CODE VARCHAR2(50) NOT NULL,
ROLE_DESCRIPTION VARCHAR2(100) DEFAULT ' ' NOT NULL,

IS_DEL CHAR(1) DEFAULT '0' NOT NULL,
CREATE_TIME	DATE NOT NULL,
UPDATE_TIME	DATE NOT NULL,
CREATE_USERID NUMBER(20) DEFAULT 0 NOT NULL,
UPDATE_USERID NUMBER(20) DEFAULT 0 NOT NULL,
    
PRIMARY KEY (ID)
);

COMMENT ON TABLE T_ROLES IS '角色';
COMMENT ON COLUMN T_ROLES.ROLE_NAME  IS '角色名称';
COMMENT ON COLUMN T_ROLES.ROLE_CODE  IS '角色代码';
COMMENT ON COLUMN T_ROLES.ROLE_DESCRIPTION  IS '角色详细信息';
COMMENT ON COLUMN T_USERS.IS_DEL  IS '是否删除(0:否, 1:删)';
COMMENT ON COLUMN T_USERS.CREATE_TIME  IS '创建时间';
COMMENT ON COLUMN T_USERS.UPDATE_TIME  IS '最后更新时间';
COMMENT ON COLUMN T_USERS.CREATE_USERID  IS '创建者ID';
COMMENT ON COLUMN T_USERS.UPDATE_USERID  IS '更新者ID';