CREATE TABLE T_AREAS
(
ID NUMBER(20) NOT NULL,
AREAS_NAME VARCHAR2(50) NOT NULL,
AREAS_HEAD_LETTER VARCHAR(1) NOT NULL,
AREAS_PARENT_ID NUMBER(20) DEFAULT 0 NOT NULL,
AREAS_SORT_NO NUMBER(3) NOT NULL,
AREAS_DEEP NUMBER(2) DEFAULT 0 NOT NULL,
PRIMARY KEY (ID)
);

COMMENT ON TABLE T_AREAS IS '地区信息表';
COMMENT ON COLUMN T_AREAS.AREAS_NAME  IS '地区名称';
COMMENT ON COLUMN T_AREAS.AREAS_HEAD_LETTER IS '地区首字母, 中文为拼音首字母';
COMMENT ON COLUMN T_AREAS.AREAS_PARENT_ID IS '上级地区ID';
COMMENT ON COLUMN T_AREAS.AREAS_SORT_NO IS '排序';
COMMENT ON COLUMN T_AREAS.AREAS_DEEP IS '地区路径深度, 如江苏省和上海市为0级地区';

CREATE INDEX INDEX_T_AREAS_PARENT_ID ON T_AREAS(AREAS_PARENT_ID);
CREATE INDEX INDEX_T_AREAS_HEAD_LETTER ON T_AREAS(AREAS_HEAD_LETTER);